#print("Hello world.")
#x = float(input("Please type a non decimal number."))
#y = float(input("Please type another non decimal number."))
#print(x + y)
#print(x - y)
#print(x * y)
#print(x / y)
#userName = input("Please type your first name.")
#print("Hello " + userName +"!")
#birthYear = float(input("Please type in your birth year."))
#age = 2025 - birthYear
#print("You are turning", age, "this year.")
#capital = input("Type a word.")
#print(capital.upper())
favorite = input("Type in your favorite word.")
print(len(favorite))